### ISSUE TITLE
Fix random map issue, chose the right files.

### ISSUE THREAD

**Issue by SticksDev** [dev-launchers-sandbox/community-minecraft#56]

**Comment by SticksDev** [comment]
Possible fix: nuke the server.properties file, this should cause it to scan its dir and look for world files.

After we do that manually, if it fixes it, re upload the new server.properties file.

Commands: `rm server.properties ` in the server dir.

**Comment by chungthuang** [comment]
What is the random map issue, and on what bases makes us think deleting `server.properties` will fix it?

**Comment by SticksDev** [comment]
Fixed in #62
