### ISSUE TITLE
Add Frog Resource Pack

### ISSUE THREAD

**Issue by MaxWiens** [dev-launchers-sandbox/community-minecraft#63]
This is a feature which some users wanted and was given the go-ahead by @pyxld-kris to be put into the server.

**Some Info:**
Servers which use a set resource pack need an available download link to the .zip file. We shouldn't just set the server resource pack to this frog one because we will add additional textures/resources in the future. Therefore we will need to host this resource pack somewhere, whether that be on Github, a DevLaunchers server, or some a hosting platform.

Instructions on how to add a resource pack to a server can be found **[here](https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack#Server_Resource_Packs)**.
The resource pack forum post (and download) can be found **[here](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/2872846-forgs-resource-pack-add-frogs-to-minecraft)**.

If someone else doesn't add this in the next week, I'll submit a pull request with the feature added when I have more free time.

**Comment by dr-hextanium** [comment]
make everything a frog yes

**Comment by pyxld-kris** [comment]
This is great info, thank you Max!

**Comment by pyxld-kris** [comment]
I think we can probably serve this up from Github, potentially with a clever combination of GitHub Actions and GitHub Pages

**Comment by SticksDev** [comment]
@MaxWiens @pyxld-kris It seems this won't work, bacause of the pack only working on `1.12` as we are on `1.16.4`

**Comment by pyxld-kris** [comment]
@Thatcooldevguy What are our alternative options?

**Comment by SticksDev** [comment]
hmm, let me look into it.

**Comment by TechnoDrive** [comment]
> @MaxWiens @pyxld-kris It seems this won't work, bacause of the pack only working on `1.12` as we are on `1.16.4`

Exactly what "pack" are you referencing here.

**Comment by MaxWiens** [comment]
@Thatcooldevguy I have updated the resource pack. The updated pack is in the minecraft-devs channel of the Dev Launchers discord.
Here is a direct link: https://cdn.discordapp.com/attachments/781684450957197322/785363465732620298/FORGS.zip

**Comment by SticksDev** [comment]
@MaxWiens Alright, I'll add it.

**Comment by pyxld-kris** [comment]
This issue is solved. We have a new repository with a new custom resource pack which works with the latest version of minecraft [HERE](https://github.com/dev-launchers/minecraft__pack)
