### ISSUE TITLE
Next meeting topic list

### ISSUE THREAD

**Issue by SticksDev** [dev-launchers-sandbox/community-minecraft#92]
Timed Manitance
Logs

**Comment by SticksDev** [comment]
Staus site
WorldGuard

**Comment by SticksDev** [comment]
How is backup system is setup, auto deploy plugins from github

**Comment by SticksDev** [comment]
Update paper to build 304

**Comment by SticksDev** [comment]
Setting up stageing server

**Comment by chungthuang** [comment]
I suggest making each topic an issue with detailed description.

**Comment by SticksDev** [comment]
co inspect (HIGH)

**Comment by SticksDev** [comment]
> I suggest making each topic an issue with a detailed description.

I know the reason for most of these, And after we talk about it, we can split them
